config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/signup' => 'users#new', as: :signup
  
  resources :users do
    resources :books do
      resources :reviews
    end
  end

  resources :books do
    resources :reviews
    resources :favorites
  end

  resources :reviews
end

app/models/book.rb
class Book < ActiveRecord::Base
  
  has_many :reviews
  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user

  validates :title, :author, :one_liner, :cover_url, :summary, 
    presence: true, 
    allow_blank: false,
    allow_nil: false

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ActiveRecord::Base
  
  belongs_to :book
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name, :username, :email
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to root_path unless current_user
  end

  def current_user
    @currect_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authorize

  def index
    @books = Book.all
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create

    Favorite.create(favorite_params)
    # fav.user = current_user
    redirect_to books_path
  end

private

  def favorite_params
    params.permit(:book_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    user = User.find(params[:user_id])
    book = Book.find(params[:book_id])
    @review = Review.new(user_id: user.id, book_id: book.id)
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to books_path
    else
      flash[:error] = @review.errors.full_messages
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:user_id, :book_id, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])

    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to books_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to books_path
    else
      render :new
    end
  end

private
  
  def user_params
    params.require(:user).permit(:password, :password_confirmation, :username, :email, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<div class="card" id="book-<%= book.id %>">
  <div class="card-image">
    <%= image_tag book.cover_url %>
  </div>
  <div class="card-header">
    <%= book.title %>
    <p><em>by <%= book.author %></em></p>
  </div>
  <div class="card-copy">
    <p><%= book.one_liner %></p>
    <p class="review-count"><%= book.reviews.count %> reviews</p>
<!--     <p><%= button_to "Add your thoughts", new_user_book_review_path(book_id: book, user_id: current_user), method: :get %></p> -->
    <p>
      <% if book.favorited_users.include?(current_user) %>
        <%= fa_icon 'star 2x', class: 'favorited' %>
      <% else %>  
        <%= link_to fa_icon('star 2x'), book_favorites_path(book_id: book.id, user_id: current_user.id), method: :post %>
      <% end %>
    </p>
  </div>
</div>

app/views/books/index.html.erb
<h1>READ ALL THE BOOKS!</h1>
<%= fa_icon 'book 3x' %>
<div class='cards'>
  <% @books.each do |book| %>
    <%= render partial: 'book', locals: { book: book } %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Welcome to Shakespeare</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shakespeare</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= link_to 'Logout', logout_path %>
  <% else %>
    <%= link_to 'Login', login_path %> or <%= link_to 'Sign Up', signup_path %>
  <% end %>

  <% flash.each do |key,msg| %>
    <div class="flash-<%= key %>">
      <span><%= msg %></span>
    </div>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/reviews/_review_form.html.erb
<%= form_for review do |f| %>
  <%= f.text_field :body %>
  <%= f.hidden_field :book_id, hidden: true %>
  <%= f.hidden_field :user_id, hidden: true %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= render partial: 'review_form', locals: { review: @review } %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: 'Your name' %>
  <%= f.text_field :email, placeholder: 'Your email' %>
  <%= f.text_field :username, placeholder: 'Username' %>
  <%= f.password_field :password, placeholder: 'Password' %>
  <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
  <%= f.submit "Join" %>
<% end %>